feat(harborApi): add ability to overwrite apis
turnerlabs/harbor-compose pull request #91
Opened 2017-05-01 22:21 UTC by jkurz

* add ability to overwrite default APIs with environment variables

2017-05-02 13:50 UTC, jritsema requested changes
Looks good.  Can you add a couple tests that verify the resulting endpoints?

2017-05-02 13:50 UTC, jritsema commented on cmd/harborAPI.go
> +// SetHarborValues will set the default values
comment is out of date

2017-05-02 13:50 UTC, jritsema commented on cmd/harborAPI.go
>  var triggerURI = "http://harbor-trigger.services.dmtio.net"
Do the other endpoints use a naming convention?

2017-05-02 13:53 UTC, jkurz commented on cmd/harborAPI.go
>  var triggerURI = "http://harbor-trigger.services.dmtio.net"
Yes. actually everything uses the same convention.

```
http://${PRODUCT}.${ENVIRONMENT}.services.ec2.dmtio.net
```

2017-05-03 13:29 UTC, jritsema submitted a review, later dismissed
LGTM

2017-05-03 19:57 UTC, wilsonodk reviewed
I really like the idea of being able to override the API addresses. Not a fan of the way the URLs are being concatenated together. I makes big assumptions on the path construction based on a singular value.

2017-05-04 12:05 UTC, jtolsma commented
+1 to being able to override API addresses... but magic decisions on 'environment' will just open up pain later if not all environments match.  Better to be explicit IMHO

2017-06-09 20:28 UTC, jkurz commented
Updated this PR to allow for overwrites via a config file. Now you can set a file in any directory and specify what urls to hit when using Harbor Compose. Example of doing this is in the CONTRIBUTING.md also in the PR.

2017-06-09 21:51 UTC, jritsema requested changes

2017-06-09 21:51 UTC, jritsema commented on cmd/harborAPI_test.go
> +func TestReadHarborEndpoints(t *testing.T) {
Tests should go in the test file (harborAPI_test.go).

2017-06-09 21:51 UTC, jritsema commented on cmd/harborAPI.go
> +func readConfig() (*Config, error) {
The config management stuff feels maybe a bit much to have in this API client file.  Should we consider moving it to a different file, something like `config.go`?  That might also make more sense should we add non-api related config things in the future.

2017-06-09 21:51 UTC, jritsema commented on CONTRIBUTING.md
>  * Run `go fmt ./...` before committing.
should probably be `go fmt ./cmd`

2017-06-09 21:54 UTC, jritsema commented
A test failed in the [last build](https://circleci.com/gh/turnerlabs/harbor-compose/309)...need to look at why the build still passed.

2017-06-12 21:21 UTC, jkurz commented on cmd/harborAPI.go
> +func readConfig() (*Config, error) {
yeah I agree.

2017-06-13 13:45 UTC, jritsema commented
LGTM

2017-06-13 13:45 UTC, jritsema approved these changes

2017-06-13 13:46 UTC, merged